### ISSUE TITLE
No users found in the group chat. Please wait a second and try again.

### ISSUE THREAD

**Issue by Mo7mud** [AlejandroAkbal/WhatsApp-Web-Mention-Everyone-Userscript#1]
It's not working, it says:

No users found in the group chat. Please wait a second and try again.

**Comment by AlejandroAkbal** [comment]
Other users are reporting that you need to have WhatsApp Web un English, try that as a workaround for now :')

**Comment by Mo7mud** [comment]
> Other users are reporting that you need to have WhatsApp Web un English, try that as a workaround for now :')

Yes it's me who reported that on Reddit and forgot to close the issue here.
Thank you very much for this awesome script, it's working like charm.

**Comment by AlejandroAkbal** [comment]
Fixed it for good, it was a Locale issue as you told me

 Please let me know if everything is all right now!

**Comment by Mo7mud** [comment]
OK it's not a local issue fortunately.
It's loading issue 
You have to press 1 `@` then wait for the list of users to appear then you press `@` again.
If you pressed `@` twice so fast before users list appears you'll get this error even with English interface.
Thank you very much
