### ISSUE TITLE
No chat input found. Please type a letter in the chat input.

### ISSUE THREAD

**Issue by EdyMarin** [AlejandroAkbal/WhatsApp-Web-Mention-Everyone-Userscript#3]
After inputting "@@" in the chat, I receive this error message. This issue arises in every chat after I first recieve this error message "No users found in the group chat. Please wait a second and try again.If the error persists, it might be that your Locale is not supported. Please open an issue on GitHub."

**Comment by AlejandroAkbal** [comment]
What's your locale, also can you send a screenshot?

**Comment by EdyMarin** [comment]
![Screenshot 2023-12-09 212444](https://github.com/AlejandroAkbal/WhatsApp-Web-Mention-Everyone-Userscript/assets/29956207/fbcd1b49-4258-41e6-b9b4-27474410535b)
![Screenshot 2023-12-09 212653](https://github.com/AlejandroAkbal/WhatsApp-Web-Mention-Everyone-Userscript/assets/29956207/6ed28a7f-6480-4755-8db0-258d74661de5)

What do you mean by locale? Location?

**Comment by AlejandroAkbal** [comment]
No, your WhatsApp web language

Those screenshots tell me nothing, could you try and see if you have the latest version installed of the userscript? 0.1.4

**Comment by EdyMarin** [comment]
Yes, I am running the latest version (0.1.4).

How do I find the locale?

**Comment by AlejandroAkbal** [comment]
Just tell me what language the WhatsApp web interface is on


Alejandro Akbal
akbal.dev <https://akbal.dev>



Dec 9, 2023, 20:12 by ***@***.***:

**Comment by EdyMarin** [comment]
English (UK I think)

**Comment by AlejandroAkbal** [comment]
Its working for me, only thing I can think of is that whatsapp web is doing A/B testing and your whatsapp web version is different than mine

Which in that case I can't do much

If you know something about coding please try modifying these two lines
https://github.com/AlejandroAkbal/WhatsApp-Web-Mention-Everyone-Userscript/blob/0f60fd44cb7b2e2bed39534c4ed28d81d2c33630/src/main.user.js#L52
https://github.com/AlejandroAkbal/WhatsApp-Web-Mention-Everyone-Userscript/blob/0f60fd44cb7b2e2bed39534c4ed28d81d2c33630/src/main.user.js#L82

**Comment by g4b3ll** [comment]
Hello friend, im having the same error here:

![image](https://github.com/AlejandroAkbal/WhatsApp-Web-Mention-Everyone-Userscript/assets/32038696/8eb9ea4e-35d4-45e3-8c30-687566089d10)

loc="pt-BR" lang="pt-BR"

**Comment by jianmingsu** [comment]
change line 82 to this: const chatInput = document.querySelector('div[contenteditable="true"]');
this worked for me

**Comment by g4b3ll** [comment]
Ok, ill try, thx!!!

**Comment by jianmingsu** [comment]
i just find out there is a problem with the code. it did input everyone in group automatically but you still have to select them manually afterwards otherwise they wont get a notification. i will see if i can find a solution

**Comment by g4b3ll** [comment]
They get marked at least?

**Comment by g4b3ll** [comment]
I thought that maybe some update changed the css selector, or html

**Comment by Sammyboi74** [comment]
> i just find out there is a problem with the code. it did input everyone in group automatically but you still have to select them manually afterwards otherwise they wont get a notification. i will see if i can find a solution

I am having the same issue....

**Comment by AlejandroAkbal** [comment]
Unfortunately, my WhatsApp web behaves correctly, so I can't debug and fix your case, if you got some technical abilities, try this:

> Its working for me, only thing I can think of is that whatsapp web is doing A/B testing and your whatsapp web version is different than mine
> 
> Which in that case I can't do much
> 
> If you know something about coding please try modifying these two lines
> 
> https://github.com/AlejandroAkbal/WhatsApp-Web-Mention-Everyone-Userscript/blob/0f60fd44cb7b2e2bed39534c4ed28d81d2c33630/src/main.user.js#L52
> 
> https://github.com/AlejandroAkbal/WhatsApp-Web-Mention-Everyone-Userscript/blob/0f60fd44cb7b2e2bed39534c4ed28d81d2c33630/src/main.user.js#L82

And post it back here so I can fix  it for everyone

**Comment by g4b3ll** [comment]
I'll try later and let you informed

**Comment by gusgrub** [comment]
People from Brasil change this 2 lines

Line 59 to:     const separator = groupSubtitle.textContent.includes('，') ? '，' : ','
Line 82 to:     const chatInput = document.querySelector('div[contenteditable="true"]');

**Comment by annitacaniglia** [comment]
I'm from Argentina but I use WhatsApp web on English. The script does not work. Error: No users found in the group chat. Please wait a second and try again.If the error persists, it might be that your Locale is not supported. Please open an issue on GitHub

**Comment by THEGAMECHANGER416** [comment]
changing line82 to this got it working for me:
`const chatInput = document.querySelector('footer div[contenteditable="true"]');`
@AlejandroAkbal Look into this, can I make a PR if needed?

**Comment by shaz8** [comment]
Hi @THEGAMECHANGER416, changing line 82 to your suggestion did not work for me. for me the generic solution that makes sense and is working is changin line 82 to `const chatInput = document.activeElement;` @AlejandroAkbal

**Comment by THEGAMECHANGER416** [comment]
> Hi @THEGAMECHANGER416, changing line 82 to your suggestion did not work for me. for me the generic solution that makes sense and is working is changin line 82 to `const chatInput = document.activeElement;` @AlejandroAkbal

Yes this seems to work for now

**Comment by AlejandroAkbal** [comment]
Ok, will add that
