### ISSUE TITLE
Not working anymore :(

### ISSUE THREAD

**Issue by matteotoma98** [AlejandroAkbal/WhatsApp-Web-Mention-Everyone-Userscript#6]
Unfortunately it's not working anymore (Chrome)
![Screen](https://github.com/AlejandroAkbal/WhatsApp-Web-Mention-Everyone-Userscript/assets/48352371/3e9b836f-285a-42fe-910d-43f49f9e0638)

**Comment by kaitou1412** [comment]
In group chat, when I type "@@", It Prompts:
No chat subtitle found. Please open a group chat.

can you help fix it?

**Comment by AlejandroAkbal** [comment]
@matteotoma98 please attach a console screenshot

**Comment by AlejandroAkbal** [comment]
@kaitou1412 depends on your locale, please try to change the script until it works, and if it does, paste here the solution so I can hopefully fix it for everyone

**Comment by matteotoma98** [comment]
> @matteotoma98 please attach a console screenshot
There's no console, I'm using your Tampermonkey extension.


> @matteotoma98 please attach a console screenshot

**Comment by kaitou1412** [comment]
i'm sorry, previously i used greasyfork version that is outdated (0.1.2)
Alhamdulillaah, after updated to 0.1.5 it works fine!

thank you @matteotoma98 
![U3ibUFySVL](https://github.com/AlejandroAkbal/WhatsApp-Web-Mention-Everyone-Userscript/assets/5919461/c94f7aa5-61e9-46b4-89a0-c56eb9acd496)
